import { Trailer, ToolInventoryItem, FilmSheetInventoryItem } from "../../types";
import { TOOL_INVENTORY, FILM_SHEET_TYPES } from "../../features/trailer/utils/trailerUtils";

// Helper function to generate complete tool inventory
const generateToolInventory = (): ToolInventoryItem[] => {
  return TOOL_INVENTORY.map(tool => ({
    toolName: tool.name,
    currentStock: Math.floor(Math.random() * (tool.defaultThreshold * 2)) + 1,
    threshold: tool.defaultThreshold,
    status: Math.random() > 0.7 ? 'low' : Math.random() > 0.9 ? 'critical' : 'good' as 'good' | 'low' | 'critical'
  }));
};

// Helper function to generate complete film sheet inventory
const generateFilmSheetInventory = (): FilmSheetInventoryItem[] => {
  return FILM_SHEET_TYPES.map(sheetType => ({
    sheetType,
    currentStock: Math.floor(Math.random() * 50) + 5,
    threshold: 10,
    status: Math.random() > 0.7 ? 'low' : Math.random() > 0.9 ? 'critical' : 'good' as 'good' | 'low' | 'critical'
  }));
};

export const EXPANDED_TRAILER_DATA: Trailer[] = [
  {
    id: "1",
    trailerName: "Alpha Trailer",
    registrationNumber: "REG-001-2024",
    parkingAddress: "123 Main Street",
    state: "California",
    city: "Los Angeles",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "unavailable",
    activityLogs: [],
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-16T14:20:00Z",
  },
  {
    id: "2",
    trailerName: "Beta Trailer",
    registrationNumber: "REG-002-2024",
    parkingAddress: "456 Industrial Blvd",
    state: "Texas",
    city: "Houston",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "available",
    activityLogs: [],
    createdAt: "2024-01-14T09:15:00Z",
    updatedAt: "2024-01-14T09:15:00Z",
  },
  {
    id: "3",
    trailerName: "Gamma Trailer",
    registrationNumber: "REG-003-2024",
    parkingAddress: "789 Service Road",
    state: "Florida",
    city: "Miami",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "low",
    activityLogs: [],
    createdAt: "2024-01-13T16:45:00Z",
    updatedAt: "2024-01-13T16:45:00Z",
  },
  {
    id: "4",
    trailerName: "Delta Trailer",
    registrationNumber: "REG-004-2024",
    parkingAddress: "321 Oak Avenue",
    state: "New York",
    city: "New York",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "available",
    activityLogs: [],
    createdAt: "2024-01-12T08:30:00Z",
    updatedAt: "2024-01-12T08:30:00Z",
  },
  {
    id: "5",
    trailerName: "Echo Trailer",
    registrationNumber: "REG-005-2024",
    parkingAddress: "654 Pine Street",
    state: "Illinois",
    city: "Chicago",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "low",
    activityLogs: [],
    createdAt: "2024-01-11T14:20:00Z",
    updatedAt: "2024-01-11T14:20:00Z",
  },
  {
    id: "6",
    trailerName: "Foxtrot Trailer",
    registrationNumber: "REG-006-2024",
    parkingAddress: "987 Elm Drive",
    state: "Arizona",
    city: "Phoenix",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "available",
    activityLogs: [],
    createdAt: "2024-01-10T11:45:00Z",
    updatedAt: "2024-01-10T11:45:00Z",
  },
  {
    id: "7",
    trailerName: "Golf Trailer",
    registrationNumber: "REG-007-2024",
    parkingAddress: "147 Cedar Lane",
    state: "Colorado",
    city: "Denver",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "low",
    activityLogs: [],
    createdAt: "2024-01-09T16:10:00Z",
    updatedAt: "2024-01-09T16:10:00Z",
  },
  {
    id: "8",
    trailerName: "Hotel Trailer",
    registrationNumber: "REG-008-2024",
    parkingAddress: "258 Maple Court",
    state: "Washington",
    city: "Seattle",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "available",
    activityLogs: [],
    createdAt: "2024-01-08T09:25:00Z",
    updatedAt: "2024-01-08T09:25:00Z",
  },
  {
    id: "9",
    trailerName: "India Trailer",
    registrationNumber: "REG-009-2024",
    parkingAddress: "369 Birch Street",
    state: "Oregon",
    city: "Portland",
    inventory: {
      tools: generateToolInventory(),
      filmSheets: generateFilmSheetInventory(),
    },
    status: "low",
    activityLogs: [],
    createdAt: "2024-01-07T13:40:00Z",
    updatedAt: "2024-01-07T13:40:00Z",
  },
  {
    id: "10",
    trailerName: "Juliet Trailer",
    registrationNumber: "REG-010-2024",
    parkingAddress: "741 Spruce Avenue",
    state: "Nevada",
    city: "Las Vegas",
    inventory: {
      tools: [
        { toolName: "CART", currentStock: 7, threshold: 6, status: "good" },
        { toolName: "BEER TANK W/ HOSE", currentStock: 6, threshold: 6, status: "good" },
        { toolName: "HARD PRESS", currentStock: 6, threshold: 6, status: "good" },
        { toolName: "RED CARD", currentStock: 7, threshold: 6, status: "good" },
      ],
      filmSheets: [
        { sheetType: "BR", currentStock: 30, threshold: 20, status: "good" },
        { sheetType: "Riot+", currentStock: 22, threshold: 20, status: "good" },
        { sheetType: "Riot", currentStock: 16, threshold: 15, status: "good" },
      ],
    },
    status: "available",
    activityLogs: [],
    createdAt: "2024-01-06T10:15:00Z",
    updatedAt: "2024-01-06T10:15:00Z",
  },
  {
    id: "11",
    trailerName: "Kilo Trailer",
    registrationNumber: "REG-011-2024",
    parkingAddress: "852 Willow Way",
    state: "Utah",
    city: "Salt Lake City",
    inventory: {
      tools: [
        { toolName: "CART", currentStock: 3, threshold: 6, status: "low" },
        { toolName: "BEER TANK W/ HOSE", currentStock: 2, threshold: 6, status: "low" },
        { toolName: "HARD PRESS", currentStock: 1, threshold: 6, status: "low" },
        { toolName: "RED CARD", currentStock: 2, threshold: 6, status: "low" },
      ],
      filmSheets: [
        { sheetType: "BR", currentStock: 6, threshold: 20, status: "low" },
        { sheetType: "Riot+", currentStock: 4, threshold: 20, status: "low" },
        { sheetType: "Riot", currentStock: 2, threshold: 15, status: "low" },
      ],
    },
    status: "low",
    activityLogs: [],
    createdAt: "2024-01-05T15:30:00Z",
    updatedAt: "2024-01-05T15:30:00Z",
  },
  {
    id: "12",
    trailerName: "Lima Trailer",
    registrationNumber: "REG-012-2024",
    parkingAddress: "963 Poplar Drive",
    state: "Montana",
    city: "Billings",
    inventory: {
      tools: [
        { toolName: "CART", currentStock: 6, threshold: 6, status: "good" },
        { toolName: "BEER TANK W/ HOSE", currentStock: 6, threshold: 6, status: "good" },
        { toolName: "HARD PRESS", currentStock: 6, threshold: 6, status: "good" },
        { toolName: "RED CARD", currentStock: 6, threshold: 6, status: "good" },
      ],
      filmSheets: [
        { sheetType: "BR", currentStock: 25, threshold: 20, status: "good" },
        { sheetType: "Riot+", currentStock: 20, threshold: 20, status: "good" },
        { sheetType: "Riot", currentStock: 15, threshold: 15, status: "good" },
      ],
    },
    status: "available",
    activityLogs: [],
    createdAt: "2024-01-04T12:00:00Z",
    updatedAt: "2024-01-04T12:00:00Z",
  },
  {
    id: "13",
    trailerName: "Mike Trailer",
    registrationNumber: "REG-013-2024",
    parkingAddress: "159 Ash Street",
    state: "Wyoming",
    city: "Cheyenne",
    inventory: {
      tools: [
        { toolName: "CART", currentStock: 5, threshold: 6, status: "low" },
        { toolName: "BEER TANK W/ HOSE", currentStock: 4, threshold: 6, status: "low" },
        { toolName: "HARD PRESS", currentStock: 3, threshold: 6, status: "low" },
        { toolName: "RED CARD", currentStock: 5, threshold: 6, status: "low" },
      ],
      filmSheets: [
        { sheetType: "BR", currentStock: 12, threshold: 20, status: "low" },
        { sheetType: "Riot+", currentStock: 8, threshold: 20, status: "low" },
        { sheetType: "Riot", currentStock: 6, threshold: 15, status: "low" },
      ],
    },
    status: "low",
    activityLogs: [],
    createdAt: "2024-01-03T14:45:00Z",
    updatedAt: "2024-01-03T14:45:00Z",
  },
  {
    id: "14",
    trailerName: "November Trailer",
    registrationNumber: "REG-014-2024",
    parkingAddress: "357 Hickory Lane",
    state: "Idaho",
    city: "Boise",
    inventory: {
      tools: [
        { toolName: "CART", currentStock: 8, threshold: 6, status: "good" },
        { toolName: "BEER TANK W/ HOSE", currentStock: 7, threshold: 6, status: "good" },
        { toolName: "HARD PRESS", currentStock: 8, threshold: 6, status: "good" },
        { toolName: "RED CARD", currentStock: 9, threshold: 6, status: "good" },
      ],
      filmSheets: [
        { sheetType: "BR", currentStock: 38, threshold: 20, status: "good" },
        { sheetType: "Riot+", currentStock: 32, threshold: 20, status: "good" },
        { sheetType: "Riot", currentStock: 24, threshold: 15, status: "good" },
      ],
    },
    status: "available",
    activityLogs: [],
    createdAt: "2024-01-02T08:20:00Z",
    updatedAt: "2024-01-02T08:20:00Z",
  },
  {
    id: "15",
    trailerName: "Oscar Trailer",
    registrationNumber: "REG-015-2024",
    parkingAddress: "468 Chestnut Road",
    state: "New Mexico",
    city: "Albuquerque",
    inventory: {
      tools: [
        { toolName: "CART", currentStock: 4, threshold: 6, status: "low" },
        { toolName: "BEER TANK W/ HOSE", currentStock: 3, threshold: 6, status: "low" },
        { toolName: "HARD PRESS", currentStock: 2, threshold: 6, status: "low" },
        { toolName: "RED CARD", currentStock: 4, threshold: 6, status: "low" },
      ],
      filmSheets: [
        { sheetType: "BR", currentStock: 10, threshold: 20, status: "low" },
        { sheetType: "Riot+", currentStock: 7, threshold: 20, status: "low" },
        { sheetType: "Riot", currentStock: 5, threshold: 15, status: "low" },
      ],
    },
    status: "low",
    activityLogs: [],
    createdAt: "2024-01-01T11:10:00Z",
    updatedAt: "2024-01-01T11:10:00Z",
  },
];
